# Generated by Django 3.1 on 2020-09-24 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ubicacion',
            new_name='Categoria',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='Ubicaciones',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categorias',
            field=models.ManyToManyField(help_text='Seleccione las categorias', to='blog.Categoria'),
        ),
    ]
